descriptionFormat: ''
handle: clothing
hasDimensions: true
hasProductTitleField: true
hasVariantTitleField: true
hasVariants: false
name: Clothing
productTitleFormat: ''
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # $SITE_NAME
    hasUrls: true
    template: shop/products/_product
    uriFormat: 'shop/products/{slug}'
skuFormat: ''
titleFormat: '{product.title}'
