contentColumnType: integer(10)
fieldGroup: d6925b98-6052-4ffd-ae6a-88baebdade5b # Company Fields
handle: cmEmployerContribution
instructions: null
name: 'Employer Contribution ( % )'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
