contentColumnType: smallint(2)
fieldGroup: d6925b98-6052-4ffd-ae6a-88baebdade5b # Company Fields
handle: cmPayPeriodEnd
instructions: null
name: 'Day in Month Following Pay Period End ( 1 - 31 )'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: 31
  min: 1
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
