contentColumnType: datetime
fieldGroup: d6925b98-6052-4ffd-ae6a-88baebdade5b # Company Fields
handle: cmStagingDate
instructions: null
name: 'Staging Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
