contentColumnType: datetime
fieldGroup: 94b4d5ac-d7ea-4241-a6cb-92b39f482f99 # Common
handle: craftdatetest
instructions: ''
name: CraftDateTest
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
