contentColumnType: text
fieldGroup: 94b4d5ac-d7ea-4241-a6cb-92b39f482f99 # Common
handle: timeloop
instructions: ''
name: Timeloop
searchable: false
settings:
  showTime: '1'
translationKeyFormat: null
translationMethod: none
type: percipiolondon\timeloop\fields\TimeloopField
