fieldLayouts:
  70a0abcb-63e2-442a-83f9-52e51c1ca646:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: aa2262a4-02ec-401f-9cbe-fa5b29602c1c # Timeloop
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 848a56c4-4ed3-4f99-b898-775a7b8da608 # CraftDateTest
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: timeloop
hasTitleField: true
name: Timeloop
section: 0649811e-c584-4d67-be4f-b065dbea2271 # TimeLoop Test Section
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
