dateModified: 1624298264
email:
  fromEmail: development@percipio.london
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.1.1
  commerce:
    edition: pro
    enabled: true
    licenseKey: 0GEHO8SO861PDA3MA1SFZEGF
    schemaVersion: 3.3.2
  company-management:
    edition: standard
    enabled: true
    schemaVersion: 0.1.0
  cp-style-guide:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  notifications:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cases: '1'
      maxLength: '160'
      minLength: '6'
      numbers: '1'
      showStrengthIndicator: '1'
      symbols: '1'
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  timeloop:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: 60
  schemaVersion: 3.6.8
  timeZone: America/St_Johns
