dateModified: 1617130716
email:
  fromEmail: development@percipio.london
  fromName: Craft
  transportType: craft\mail\transportadapters\Sendmail
plugins:
  colour-swatches:
    edition: standard
    enabled: true
    schemaVersion: 1.4.1.1
  commerce:
    edition: pro
    enabled: true
    licenseKey: 0GEHO8SO861PDA3MA1SFZEGF
    schemaVersion: 3.2.18
  cp-style-guide:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  minify:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  notifications:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  password-policy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  twigpack:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: pro
  live: true
  name: $SITE_NAME
  retryDuration: 60
  schemaVersion: 3.6.7
  timeZone: Europe/London
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
