fieldLayoutId: '17'
handle: default
hasTitleField: true
name: Default
siteSettings:
  5da841b1-ca0d-46ff-8bb1-04d6c889ac54: # $SITE_NAME
    hasUrls: true
    template: company-management/companies/_company
    uriFormat: 'company-management/companies/{slug}'
  ec473f07-152f-423b-90df-ac425e6068a1:
    hasUrls: true
    template: company-management/companies/_company
    uriFormat: 'company-management/companies/{slug}'
titleFormat: null
uid: c5be7462-6fd5-4b77-b10b-887739f204cc # Default
